
name: Python Building

on:
   push:
     branches: [ main ]
   workflow_dispatch:

jobs:
  build-ALL:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-20.04
          - build: windows
            os: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Set commit message
        id: set_commit
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-20.04" ]; then
            echo "COMMIT_MESSAGE=$(git log --format=%B -1)" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "windows-2019" ]; then
            commit_message=$(git log --format=%B -1)
            echo "COMMIT_MESSAGE=$commit_message" >> $GITHUB_ENV
          fi
        shell: bash
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.10.11/x64

      - name: Install dependencies
        run: |
          python -m pip install pyinstaller FeishuBitableAPI configparser requests pymysql pandas mysql-connector-python --ignore-installed
          
      - name: Build executable
        run: |
          pyinstaller --onefile --hidden-import FeishuBitableAPI --hidden-import configparser --hidden-import requests --hidden-import json ADD_RECORDS_FROM_CSV.py --distpath dist/${{ matrix.os }}
          pyinstaller --onefile --hidden-import FeishuBitableAPI --hidden-import pymysql --hidden-import pandas --hidden-import configparser --hidden-import requests --hidden-import json ADD_RECORDS_FROM_SQL.py --distpath dist/${{ matrix.os }}
          pyinstaller --onefile --hidden-import FeishuBitableAPI --hidden-import pymysql --hidden-import pandas --hidden-import configparser --hidden-import requests --hidden-import json --hidden-import ADD_RECORDS_FROM_SQL FIX_RECORDS_FROM_SQL.py --distpath dist/${{ matrix.os }}
          pyinstaller --onefile --hidden-import FeishuBitableAPI --hidden-import configparser --hidden-import pymysql --hidden-import mysql.connector FIX_RECORDS_TO_SQL.py --distpath dist/${{ matrix.os }}
          pyinstaller --onefile --hidden-import FeishuBitableAPI --hidden-import pymysql --hidden-import pandas --hidden-import configparser --hidden-import requests --hidden-import json --hidden-import ADD_RECORDS_FROM_SQL UPDATE_RECORDS_FROM_SQL.py --distpath dist/${{ matrix.os }}


      - name: Upload-ubuntu-20.04
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_ALL_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/ubuntu-20.04/*

      - name: Upload-windows-2019
        if: ${{ matrix.os == 'windows-2019' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_ALL_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/windows-2019/*

  build-ADD_RECORDS_FROM_CSV:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-20.04
          - build: windows
            os: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Set commit message
        id: set_commit
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-20.04" ]; then
            echo "COMMIT_MESSAGE=$(git log --format=%B -1)" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "windows-2019" ]; then
            commit_message=$(git log --format=%B -1)
            echo "COMMIT_MESSAGE=$commit_message" >> $GITHUB_ENV
          fi
        shell: bash
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.10.11/x64

      - name: Install dependencies
        run: |
          python -m pip install pyinstaller FeishuBitableAPI configparser requests --ignore-installed
          
      - name: Build executable
        run: |
          pyinstaller --onefile --hidden-import FeishuBitableAPI --hidden-import configparser --hidden-import requests --hidden-import json ADD_RECORDS_FROM_CSV.py --distpath dist/${{ matrix.os }}

      - name: Upload-ubuntu-20.04
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_ADD_RECORDS_FROM_CSV_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/ubuntu-20.04/ADD_RECORDS_FROM_CSV

      - name: Upload-windows-2019
        if: ${{ matrix.os == 'windows-2019' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_ADD_RECORDS_FROM_CSV_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/windows-2019/ADD_RECORDS_FROM_CSV.exe

  build-ADD_RECORDS_FROM_SQL:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-20.04
          - build: windows
            os: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Set commit message
        id: set_commit
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-20.04" ]; then
            echo "COMMIT_MESSAGE=$(git log --format=%B -1)" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "windows-2019" ]; then
            commit_message=$(git log --format=%B -1)
            echo "COMMIT_MESSAGE=$commit_message" >> $GITHUB_ENV
          fi
        shell: bash
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.10.11/x64

      - name: Install dependencies
        run: |
          python -m pip install pyinstaller FeishuBitableAPI pymysql pandas configparser requests --ignore-installed
          
      - name: Build executable
        run: |
          pyinstaller --onefile --hidden-import FeishuBitableAPI --hidden-import pymysql --hidden-import pandas --hidden-import configparser --hidden-import requests --hidden-import json ADD_RECORDS_FROM_SQL.py --distpath dist/${{ matrix.os }}

      - name: Upload-ubuntu-20.04
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_ADD_RECORDS_FROM_SQL_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/ubuntu-20.04/ADD_RECORDS_FROM_SQL

      - name: Upload-windows-2019
        if: ${{ matrix.os == 'windows-2019' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_ADD_RECORDS_FROM_SQL_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/windows-2019/ADD_RECORDS_FROM_SQL.exe

  build-FIX_RECORDS_FROM_SQL:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-20.04
          - build: windows
            os: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Set commit message
        id: set_commit
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-20.04" ]; then
            echo "COMMIT_MESSAGE=$(git log --format=%B -1)" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "windows-2019" ]; then
            commit_message=$(git log --format=%B -1)
            echo "COMMIT_MESSAGE=$commit_message" >> $GITHUB_ENV
          fi
        shell: bash
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.10.11/x64

      - name: Install dependencies
        run: |
          python -m pip install pyinstaller FeishuBitableAPI pymysql pandas configparser requests --ignore-installed
          
      - name: Build executable
        run: |
          pyinstaller --onefile --hidden-import FeishuBitableAPI --hidden-import pymysql --hidden-import pandas --hidden-import configparser --hidden-import requests --hidden-import json --hidden-import ADD_RECORDS_FROM_SQL FIX_RECORDS_FROM_SQL.py --distpath dist/${{ matrix.os }}

      - name: Upload-ubuntu-20.04
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_FIX_RECORDS_FROM_SQL_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/ubuntu-20.04/FIX_RECORDS_FROM_SQL

      - name: Upload-windows-2019
        if: ${{ matrix.os == 'windows-2019' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_FIX_RECORDS_FROM_SQL_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/windows-2019/FIX_RECORDS_FROM_SQL.exe

  build-FIX_RECORDS_TO_SQL:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-20.04
          - build: windows
            os: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Set commit message
        id: set_commit
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-20.04" ]; then
            echo "COMMIT_MESSAGE=$(git log --format=%B -1)" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "windows-2019" ]; then
            commit_message=$(git log --format=%B -1)
            echo "COMMIT_MESSAGE=$commit_message" >> $GITHUB_ENV
          fi
        shell: bash
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.10.11/x64

      - name: Install dependencies
        run: |
          python -m pip install pyinstaller FeishuBitableAPI mysql-connector-python configparser pymysql --ignore-installed
          
      - name: Build executable
        run: |
          pyinstaller --onefile --hidden-import FeishuBitableAPI --hidden-import configparser --hidden-import pymysql --hidden-import mysql.connector FIX_RECORDS_TO_SQL.py --distpath dist/${{ matrix.os }}

      - name: Upload-ubuntu-20.04
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_FIX_RECORDS_TO_SQL_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/ubuntu-20.04/FIX_RECORDS_TO_SQL

      - name: Upload-windows-2019
        if: ${{ matrix.os == 'windows-2019' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_FIX_RECORDS_TO_SQL_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/windows-2019/FIX_RECORDS_TO_SQL.exe

  build-UPDATE_RECORDS_FROM_SQL:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-20.04
          - build: windows
            os: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Set commit message
        id: set_commit
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-20.04" ]; then
            echo "COMMIT_MESSAGE=$(git log --format=%B -1)" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "windows-2019" ]; then
            commit_message=$(git log --format=%B -1)
            echo "COMMIT_MESSAGE=$commit_message" >> $GITHUB_ENV
          fi
        shell: bash
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.10.11/x64

      - name: Install dependencies
        run: |
          python -m pip install pyinstaller FeishuBitableAPI pymysql pandas configparser requests --ignore-installed
          
      - name: Build executable
        run: |
          pyinstaller --onefile --hidden-import FeishuBitableAPI --hidden-import pymysql --hidden-import pandas --hidden-import configparser --hidden-import requests --hidden-import json --hidden-import ADD_RECORDS_FROM_SQL UPDATE_RECORDS_FROM_SQL.py --distpath dist/${{ matrix.os }}

      - name: Upload-ubuntu-20.04
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_UPDATE_RECORDS_FROM_SQL_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/ubuntu-20.04/UPDATE_RECORDS_FROM_SQL

      - name: Upload-windows-2019
        if: ${{ matrix.os == 'windows-2019' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_UPDATE_RECORDS_FROM_SQL_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/windows-2019/UPDATE_RECORDS_FROM_SQL.exe